language: minimal

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_3d8740c492aa_key -iv $encrypted_3d8740c492aa_iv -in passport.json.enc -out passport.json -d

script:
  - docker build . -t lego-e2e
  - docker run lego-e2e
